version: "3"

services:
  catkin_ws:
    container_name: "catkin_ws"
    image: 6dc2632f1f43
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /root/catkin_ws/src:/root/catkin_ws
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true